name: my-snap # you probably want to 'snapcraft register <name>'
base: core22 # the base snap is the execution environment for this snap
version: '0.1' # just for humans, typically '1.2+git' or '1.3.2'
summary: Hello-world # 79 char long summary
description: |
  print Hello-World.

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots

parts:
  my-snap:
    # See 'snapcraft plugins'
    plugin: autotools
    #source-type: local
    source: https://github.com/AnandKyabani/snap.git
    # bluid packages:
    #   - gcc
      
apps:
  my-snap:
    command: bin/my-snap

# name: moon-buggy
# base: core22
# version: '1.0.51'
# summary: Drive a car across the moon
# description: |
#   Moon-buggy is a simple character graphics game, where you drive some
#   kind of car across the moon's surface. Unfortunately there are 
#   dangerous craters there. Fortunately your car can jump over them!

# confinement: devmode

# parts:
#   moon-buggy:
#     plugin: autotools
#     autotools-configure-parameters: ["--prefix=/usr"]
#     source: https://github.com/sergiusens/moon-buggy.git
#     build-packages:
#       - libncurses-dev
#       - texinfo
# apps:
#   moon-buggy:
#     command: usr/bin/moon-buggy
